spring:
  application:
    name: ms-payments
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/vendas_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.lob.non_contextual_creation: true
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://serviceregistry:8761/eureka
  instance:
    hostname: ms-payment
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

app:
  rabbitmq:
    exchange: payments.exchange
    queue-order: order.payment.queue
    queue-payment-response: payment.response.queue
    routing-key-order: order.payment
    routing-key-payment-response: payment.response