version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_sales_ms
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendas_db
    ports:
      - "5433:5432"
    volumes:
      - sales_ms_pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # Porta AMQP para aplicação
      - "15672:15672" # Porta Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  serviceregistry:
    build: ./serviceregistry
    container_name: serviceregistry
    ports:
      - "8761:8761"
    networks:
      - app_network

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    ports:
      - "8080:8080"
    depends_on:
      - serviceregistry
    networks:
      - app_network

  ms-product:
    build: ./ms-product
    container_name: ms-product
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=ms-product
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vendas_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - serviceregistry
    networks:
      - app_network

  ms-order:
    build: ./ms-order
    container_name: ms-order
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=ms-order
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pedidos_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - serviceregistry
      - rabbitmq
    networks:
      - app_network

  ms-payment:
    build: ./ms-payments
    container_name: ms-payment
    environment:
      - SERVER_PORT=8083
      - SPRING_APPLICATION_NAME=ms-payment
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vendas_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - serviceregistry
      - rabbitmq
    networks:
      - app_network

volumes:
  sales_ms_pgdata:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge